version: '3.8'

services:
  time-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: time-tracker-app
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/database/time_tracker.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
